######################################################################
# Automatically generated by qmake (2.01a) Sat Nov 26 20:15:24 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /usr/include/qwt
LIBS += -L/usr/lib -lqwt

# Input
HEADERS += experiment.h allwaysStayPlot.h
SOURCES += experiment.cpp main.cpp allwaysStayPlot.cpp
